development: &defaults
  languages:
    en: "English"
    es: "Español"
  database:
    adapter: mysql
    host: localhost
    username: root
    password:
    database: rubyconfar_development

test:
  <<: *defaults
  database:
    adapter: sqlite3
    database: db/test.db

production:
  development